#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

# This file is part of StaplerTweet.
#
# StaplerTweet is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# StaplerTweet is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with StaplerTweet.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2013 William Denton

# CONFIGURING
#
# Configuration details are set in the file config.json.
# Make a copy of config.json.example and edit it.

require 'json'
require 'open-uri'
require 'logger'
require 'optparse'

require 'rubygems'
require 'twitter'

options = {}
options[:verbose] = false
options[:notweet] = false
OptionParser.new do |opts|
  opts.banner = "Usage: staplertweet [--notweet] [--verbose]"
  opts.on("--notweet", "Do not actually tweet anything") { options[:notweet] = true }
  opts.on("--verbose", "Be verbose") { options[:verbose] = true }
end.parse!

logger = Logger.new(STDOUT)
if options[:verbose]
  logger.level = Logger::DEBUG
else
  logger.level = Logger::INFO
end

if options[:notweet]
  logger.info "--notweet specified; no tweeting will happen"
end

# Add some randomness ... every notweet_chance% of the time, no tweet will happen
notweet_chance = 25

settings = {}

script_directory = File.dirname(__FILE__)

config_file = "#{script_directory}/config.json"
logger.debug "Config file: #{config_file}"

begin
  settings = JSON.parse(File.read(config_file))
rescue Exception => e
  STDERR.puts "No readable config.json settings file: #{e}"
  exit
end

Twitter.configure do |config|
  config.consumer_key       = settings["consumer_key"]
  config.consumer_secret    = settings["consumer_secret"]
  config.oauth_token        = settings["access_token"]
  config.oauth_token_secret = settings["access_token_secret"]
end

# There's not much to this script.

# First, get a random library stapler status
# This talks to the API and gets back an array of numbers and statuses,
# and then .sample picks one of them at random
status = JSON.parse(open("http://librarystapler.herokuapp.com/").read).sample

# Construct the tweet
tweet = "Stapler #{status['number']} is #{status['condition']}"

logger.debug "'#{tweet}'"

# Tweet it

unless options[:notweet]
  begin
    if rand(1..100) <= notweet_chance
      logger.debug "Randomly decided not to tweet"
    else
      Twitter.update(tweet) 
    end
  rescue Exception => e
    logger.error "Error tweeting (#{tweet}): #{e}"
  end
end
